platform :ios, '7.0'
inhibit_all_warnings!

pod 'FXBlurView', :head
pod 'Typhoon', '~> 1.5.3'
pod 'PayPal-iOS-SDK', '~> 1.3.5'
pod 'MSDynamicsDrawerViewController', '~> 1.0.0'
pod 'SDWebImage', '~> 3.5'
pod 'Parse-iOS-SDK', '~> 1.2.16'
pod 'sendgrid', '~> 0.1.0'
#pod 'RestKit', '~> 0.20.3'
pod 'PNChart', '~> 0.1.8'
